### ISSUE TITLE
Error: TransportError(NoAddressFound)

### ISSUE THREAD

**Issue by songtianyi** [paritytech/jsonrpsee#255]
jsonrpsee new client report error on vaild wss address
To reproduce the error
```rust
use jsonrpsee_types::{
	jsonrpc::{JsonValue, Params},
	traits::Client,
};
use jsonrpsee_ws_client::{WsClient, WsConfig};
const SERVER_URI: &str = "wss://pc2-rpc.darwinia.network";


#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {

	let client = WsClient::new(WsConfig::with_url(SERVER_URI)).await?;
        println!("OK");
	Ok(())
}
```
```toml
[package]
name = "ws-rpc-test"
version = "0.1.0"
authors = ["songtianyi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonrpsee-ws-client = "0.2.0-alpha.2"
jsonrpsee-types = "0.2.0-alpha.3"
[dependencies.tokio]
package = "tokio"
version = "0.2.22"
features = ["full"]
```
